# Generated by Django 4.1.4 on 2023-08-07 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_post_like_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='like_count',
        ),
        migrations.AddField(
            model_name='post',
            name='likecount',
            field=models.IntegerField(null=True),
        ),
    ]
